# Generated by Django 3.1.2 on 2020-10-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=8)),
                ('Telefono', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Fechanacimiento', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], default='M', max_length=1)),
                ('Importe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField()),
                ('precio_Costo', models.FloatField()),
                ('margen', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('precio_contado', models.FloatField()),
                ('precio_lista', models.FloatField()),
                ('observaciones', models.CharField(max_length=100)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='cuentacorriente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('troquel', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('Importe', models.FloatField()),
                ('observaciones', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
    ]
